apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["while true; do echo hello; sleep 10; done"]
---
kind: Secret
apiVersion: v1
metadata:
  name: example-secret2
  annotations:
    avp.kubernetes.io/path: prod/secret
type: Opaque
stringData:
  sample-secret: <foo>
